import { cancelTimeOff, reportCallOff, requestTimeOff } from "@/app/(employee)/employee/actions";
import { prisma } from "@/lib/db";
import { requirePortal } from "@/lib/rbac";
import { formatBusinessDate, formatBusinessDateTime } from "@/lib/workforce-time";

export default async function MyTimeOffPage() {
  const ctx = await requirePortal("employee");
  const employeeId = ctx.user.employeeId;
  if (!employeeId) return <p className="text-muted">No employee profile is linked.</p>;
  const now = new Date();
  const [employee, requests, callOffs, shifts] = await Promise.all([
    prisma.employee.findUnique({ where: { id: employeeId } }),
    prisma.timeOffRequest.findMany({ where: { employeeId }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.callOffRequest.findMany({ where: { employeeId }, orderBy: { reportedAt: "desc" }, take: 50 }),
    prisma.employeeShift.findMany({ where: { employeeId, status: "PUBLISHED", startsAt: { gte: now } }, orderBy: { startsAt: "asc" }, take: 30 }),
  ]);
  return <div className="space-y-8"><div><h1 className="text-3xl font-semibold text-navy">PTO & call-offs</h1><p className="mt-2 text-sm text-muted">Current PTO balance: <strong className="text-navy">{employee?.ptoBalanceHours.toString() ?? "0"} hours</strong></p></div>
    <div className="grid gap-5 xl:grid-cols-2"><form action={requestTimeOff} className="grid gap-3 rounded-2xl border border-line bg-paper p-5 sm:grid-cols-2"><h2 className="font-semibold text-navy sm:col-span-2">Request time off</h2><select name="type" className="rounded-lg border border-line px-3 py-2 text-sm"><option value="PTO">PTO</option><option value="SICK">Sick</option><option value="UNPAID">Unpaid</option><option value="BEREAVEMENT">Bereavement</option><option value="OTHER">Other</option></select><input name="hours" type="number" min="0" step="0.25" placeholder="Hours (optional)" className="rounded-lg border border-line px-3 py-2 text-sm" /><label className="text-sm">Start<input name="startDate" type="date" required className="mt-1 w-full rounded-lg border border-line px-3 py-2" /></label><label className="text-sm">End<input name="endDate" type="date" required className="mt-1 w-full rounded-lg border border-line px-3 py-2" /></label><textarea name="reason" rows={2} placeholder="Reason / note" className="rounded-lg border border-line px-3 py-2 text-sm sm:col-span-2" /><button className="w-fit rounded-full bg-navy px-4 py-2 text-sm font-semibold text-white">Submit request</button></form>
    <form action={reportCallOff} className="grid gap-3 rounded-2xl border border-line bg-paper p-5 sm:grid-cols-2"><h2 className="font-semibold text-navy sm:col-span-2">Report a call-off</h2><select name="shiftId" className="rounded-lg border border-line px-3 py-2 text-sm sm:col-span-2"><option value="">No scheduled shift selected</option>{shifts.map(s=><option key={s.id} value={s.id}>{formatBusinessDateTime(s.startsAt)} · {s.assignment ?? "Shift"}</option>)}</select><label className="text-sm sm:col-span-2">Date (required if no shift selected)<input name="callOffDate" type="date" className="mt-1 w-full rounded-lg border border-line px-3 py-2" /></label><input name="reason" required placeholder="Reason" className="rounded-lg border border-line px-3 py-2 text-sm sm:col-span-2" /><textarea name="notes" rows={2} placeholder="Additional notes" className="rounded-lg border border-line px-3 py-2 text-sm sm:col-span-2" /><button className="w-fit rounded-full bg-navy px-4 py-2 text-sm font-semibold text-white">Report call-off</button></form></div>
    <section><h2 className="text-xl font-semibold text-navy">My requests</h2><div className="mt-3 grid gap-3">{requests.length===0?<p className="text-sm text-muted">No time-off requests yet.</p>:requests.map(r=><div key={r.id} className="rounded-xl border border-line bg-paper p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium text-navy">{r.type} · {formatBusinessDate(r.startDate)} – {formatBusinessDate(r.endDate)}</p><span className="text-xs font-semibold text-muted">{r.status}</span></div>{r.managerNote?<p className="mt-2 text-sm text-muted">Manager: {r.managerNote}</p>:null}{r.status==="PENDING"?<form action={cancelTimeOff.bind(null,r.id)} className="mt-3"><button className="text-xs font-semibold text-red-700">Cancel request</button></form>:null}</div>)}</div></section>
    <section><h2 className="text-xl font-semibold text-navy">My call-offs</h2><div className="mt-3 grid gap-3">{callOffs.length===0?<p className="text-sm text-muted">No call-offs recorded.</p>:callOffs.map(c=><div key={c.id} className="rounded-xl border border-line bg-paper p-4"><p className="font-medium text-navy">{formatBusinessDate(c.callOffDate)} · {c.reason}</p><p className="mt-1 text-xs text-muted">{c.status}</p></div>)}</div></section>
  </div>;
}
