#!/usr/bin/env bash
# Idempotent Cloud Agent / local dev bootstrap for Safeway Couriers.
#
# Safe to run repeatedly and against cached or partially prepared state:
#   - installs PostgreSQL 16 only when missing
#   - creates the local dev role/database only when missing
#   - writes .env.local with local dev defaults only when missing
#   - installs npm dependencies, generates the Prisma client, applies
#     migrations, and seeds reference data (all idempotent)
#
# The credentials written here are LOCAL DEVELOPMENT ONLY (localhost Postgres,
# throwaway auth secrets generated per machine). They are not production values.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Ensuring PostgreSQL 16 is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
fi

echo "==> Starting PostgreSQL cluster"
sudo pg_ctlcluster 16 main start 2>/dev/null || true

echo "==> Waiting for PostgreSQL to accept connections"
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> Ensuring local dev role and database exist"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='safeway'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE safeway LOGIN PASSWORD 'safeway' CREATEDB;"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='safeway'" | grep -q 1 \
  || sudo -u postgres createdb -O safeway safeway

if [ ! -f .env.local ]; then
  echo "==> Writing .env.local (local dev defaults)"
  cat > .env.local <<EOF
# Generated by .cursor/install.sh for local development. Do not commit.
DATABASE_URL="postgresql://safeway:safeway@localhost:5432/safeway"
DIRECT_URL="postgresql://safeway:safeway@localhost:5432/safeway"
RUN_MIGRATE_ON_BUILD=1

NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_SITE_URL="http://localhost:3000"

BETTER_AUTH_SECRET="$(openssl rand -base64 32)"
BETTER_AUTH_URL="http://localhost:3000"
PORTAL_HOST="portal.safewaycouriers.com"

OWNER_SETUP_SECRET="$(openssl rand -hex 24)"
DATA_ENCRYPTION_KEY="$(openssl rand -base64 32)"

EMAIL_FROM="Safeway Couriers <noreply@safewaycouriers.com>"
CRON_SECRET="$(openssl rand -hex 24)"
EOF
else
  echo "==> .env.local already exists; leaving it untouched"
fi

echo "==> Installing npm dependencies"
npm install

# Prisma CLI reads .env (not .env.local); export the DB URLs for this process.
set -a
# shellcheck disable=SC1091
DATABASE_URL="$(grep -E '^DATABASE_URL=' .env.local | head -1 | cut -d= -f2- | tr -d '"')"
DIRECT_URL="$(grep -E '^DIRECT_URL=' .env.local | head -1 | cut -d= -f2- | tr -d '"')"
export DATABASE_URL DIRECT_URL
set +a

echo "==> Generating Prisma client"
npx prisma generate

echo "==> Applying database migrations"
node scripts/migrate-deploy.mjs

echo "==> Seeding reference data"
npm run db:seed

echo "==> Install complete"
