import type { Metadata } from "next";
import { createPayrollPeriod, setPayrollPeriodStatus, upsertPayrollEntry } from "@/app/(portal)/dashboard/payroll/actions";
import { prisma } from "@/lib/db";
import { formatBusinessDate } from "@/lib/workforce-time";
import { hasPermission, requirePermission } from "@/lib/rbac";

export const metadata: Metadata = { title: "Payroll" };

export default async function PayrollPage() {
  const ctx = await requirePermission("payroll.view");
  const canManage = hasPermission(ctx, "payroll.manage");
  const [employees, periods] = await Promise.all([
    prisma.employee.findMany({ where: { status: { in: ["ACTIVE", "PENDING_ONBOARDING"] } }, orderBy: [{ legalLastName: "asc" }, { legalFirstName: "asc" }] }),
    prisma.payrollPeriod.findMany({ include: { entries: { include: { employee: true }, orderBy: { employee: { legalLastName: "asc" } } } }, orderBy: { startsOn: "desc" }, take: 24 }),
  ]);
  return (
    <div className="space-y-7">
      <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-medical">Owner finance</p><h1 className="mt-2 text-3xl font-semibold text-navy">Payroll</h1><p className="mt-2 max-w-3xl text-sm text-muted">Internal payroll ledger for hours, rates, gross pay, deductions, reimbursements and pay status. It does not file payroll taxes or move money by ACH; connect a payroll provider before using it as the system of record for tax filing or direct deposit.</p></div>
      {canManage?<form action={createPayrollPeriod} className="grid gap-3 rounded-2xl border border-line bg-paper p-5 md:grid-cols-4"><h2 className="text-lg font-semibold text-navy md:col-span-4">Create pay period</h2><input name="label" placeholder="Label (e.g. Sep 1–15)" className="rounded-lg border border-line px-3 py-2 text-sm" /><label className="text-sm">Start<input name="startsOn" type="date" required className="mt-1 w-full rounded-lg border border-line px-3 py-2" /></label><label className="text-sm">End<input name="endsOn" type="date" required className="mt-1 w-full rounded-lg border border-line px-3 py-2" /></label><label className="text-sm">Pay date<input name="payDate" type="date" required className="mt-1 w-full rounded-lg border border-line px-3 py-2" /></label><button className="w-fit rounded-full bg-navy px-4 py-2 text-sm font-semibold text-white md:col-span-4">Create period</button></form>:null}
      {periods.length===0?<p className="rounded-2xl border border-dashed border-line bg-paper px-5 py-10 text-sm text-muted">No payroll periods yet.</p>:periods.map(period=><section key={period.id} className="rounded-2xl border border-line bg-paper p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-navy">{period.label}</h2><p className="text-sm text-muted">{formatBusinessDate(period.startsOn)} – {formatBusinessDate(period.endsOn)} · pay {formatBusinessDate(period.payDate)} · {period.status}</p></div>{canManage?<div className="flex gap-2">{period.status==="OPEN"?<form action={setPayrollPeriodStatus.bind(null,period.id,"PROCESSING")}><button className="rounded-full border border-line px-3 py-1.5 text-xs font-semibold">Start processing</button></form>:null}{period.status==="PROCESSING"?<form action={setPayrollPeriodStatus.bind(null,period.id,"FINALIZED")}><button className="rounded-full border border-line px-3 py-1.5 text-xs font-semibold">Finalize</button></form>:null}{period.status==="FINALIZED"?<form action={setPayrollPeriodStatus.bind(null,period.id,"PAID")}><button className="rounded-full border border-line px-3 py-1.5 text-xs font-semibold">Mark paid</button></form>:null}</div>:null}</div>
        {period.entries.length>0?<div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-muted"><tr><th className="py-2 pr-4">Employee</th><th className="py-2 pr-4">Regular</th><th className="py-2 pr-4">OT</th><th className="py-2 pr-4">Gross</th><th className="py-2 pr-4">Net</th><th className="py-2">Status</th></tr></thead><tbody>{period.entries.map(entry=><tr key={entry.id} className="border-t border-line"><td className="py-2 pr-4">{entry.employee.legalFirstName} {entry.employee.legalLastName}</td><td className="py-2 pr-4">{entry.regularHours.toString()} @ {"$"}{entry.regularRate.toString()}</td><td className="py-2 pr-4">{entry.overtimeHours.toString()} @ {"$"}{entry.overtimeRate.toString()}</td><td className="py-2 pr-4">{"$"}{entry.grossPay.toString()}</td><td className="py-2 pr-4">{"$"}{entry.netPay.toString()}</td><td className="py-2">{entry.status}</td></tr>)}</tbody></table></div>:<p className="mt-4 text-sm text-muted">No employee entries yet.</p>}
        {canManage && !["FINALIZED","PAID"].includes(period.status)?<form action={upsertPayrollEntry.bind(null,period.id)} className="mt-5 grid gap-3 border-t border-line pt-5 md:grid-cols-4"><h3 className="font-semibold text-navy md:col-span-4">Add or update employee pay</h3><select name="employeeId" required className="rounded-lg border border-line px-3 py-2 text-sm md:col-span-2"><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.legalFirstName} {e.legalLastName}{e.basePayRate ? " · base $" + e.basePayRate.toString() : ""}</option>)}</select><select name="status" className="rounded-lg border border-line px-3 py-2 text-sm"><option value="DRAFT">Draft</option><option value="APPROVED">Approved</option><option value="PAID">Paid</option></select><input name="externalReference" placeholder="External ref" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="regularHours" type="number" min="0" step="0.01" placeholder="Regular hours" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="regularRate" type="number" min="0" step="0.01" placeholder="Regular rate" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="overtimeHours" type="number" min="0" step="0.01" placeholder="OT hours" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="overtimeRate" type="number" min="0" step="0.01" placeholder="OT rate" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="deductions" type="number" min="0" step="0.01" placeholder="Deductions" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="reimbursements" type="number" min="0" step="0.01" placeholder="Reimbursements" className="rounded-lg border border-line px-3 py-2 text-sm" /><input name="notes" placeholder="Notes" className="rounded-lg border border-line px-3 py-2 text-sm md:col-span-2" /><button className="w-fit rounded-full bg-navy px-4 py-2 text-sm font-semibold text-white md:col-span-4">Save employee pay</button></form>:null}
      </section>)}
    </div>
  );
}
